name: check

env:
  DENO_VERSION: 1.x

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 0"
  push:
    branches:
      - main
    paths:
      - '**/*.ts'
      - 'deno.jsonc'
      - '.github/workflows/check.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.ts'
      - 'deno.jsonc'
      - '.github/workflows/check.yaml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: 'blob:none'
          persist-credentials: false

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Check
        run: deno task check
